version: 2.1
jobs:
  test:
    docker:
      - image: 'cimg/ruby:2.7.3'
    steps:
      - checkout
      - run:
          name: install dependencies
          command: bundle install --jobs=4
      - run:
          name: run tests
          command: bundle exec rake
workflows:
  bundle_and_test:
    jobs:
      - test
