require "active_support/core_ext/string/inflections"

module PopuliAPI
  API_TASKS = Set.new(%w[
    addAddress
    addAdvisorToStudent
    addAidApplication
    addApplication
    addApplicationNote
    addAssignmentComment
    addCampusToStudent
    addCommunicationPlanToPerson
    addCourseBulletinBoardPost
    addCourseInstanceAssignment
    addCourseInstanceAssignmentGroup
    addCourseOfferingLink
    addDefaultTuitionScheduleToStudent
    addDonation
    addEmailAddress
    addEnrollment
    addFieldOfStudy
    addFinancialAidAward
    addFinancialAidDisbursement
    addFinancialAidRefund
    addInquiry
    addOrganization
    addOrganizationToPerson
    addPayment
    addPendingCharge
    addPerson
    addPersonRelationship
    addPhoneNumber
    addProfilePicture
    addRole
    addStandardizedTestToStudent
    addStudentDegree
    addStudentDegreeSpecialization
    addStudentProgram
    addTag
    addTermTuitionScheduleToStudent
    addTodo
    addTransferCredit
    addTransferCreditProgram
    addUser
    blockUser
    createCourseInstanceMeeting
    createFinancialAidDisbursementBatch
    deleteAddress
    deleteApplication
    deleteCampusFromStudent
    deleteCommunicationPlanFromPerson
    deleteCourseInstanceAssignment
    deleteCourseInstanceAssignmentGroup
    deleteCourseOfferingLink
    deleteCustomField
    deleteEmailAddress
    deleteFinancialAidAward
    deleteFinancialAidDisbursement
    deleteFinancialAidRefund
    deleteLicensePlate
    deletePersonBirthDate
    deletePersonCitizenship
    deletePersonHometown
    deletePersonOrganization
    deletePersonRaceEthnicity
    deletePersonRelationship
    deletePersonSIN
    deletePersonSSN
    deletePhoneNumber
    deleteStudentDegreeSpecialization
    deleteStudentMealPlan
    deleteStudentRoomPlan
    deleteStudentStandardizedTest
    deleteStudentStandardizedTestSectionScore
    deleteTodo
    downloadBackup
    downloadFile
    downloadStudentSchedule
    editAidApplication
    editDonation
    editFinancialAidAward
    editFinancialAidDisbursement
    editFinancialAidRefund
    editTransferCreditProgram
    finalizeCourseInstance
    getAcademicTerms
    getAcademicYears
    getAidApplication
    getAidApplicationForStudentAidYear
    getAllCustomFields
    getAppeals
    getApplication
    getApplicationFieldOptions
    getApplicationFields
    getApplicationTemplates
    getApplications
    getAssignmentComments
    getAvailableRoles
    getCOACategories
    getCampaigns
    getCampusLifeRooms
    getCampuses
    getCommunicationPlans
    getCountries
    getCourseCatalog
    getCourseGroupInfo
    getCourseGroups
    getCourseInstance
    getCourseInstanceAssignmentGroups
    getCourseInstanceAssignments
    getCourseInstanceFiles
    getCourseInstanceLessons
    getCourseInstanceMeetingAttendance
    getCourseInstanceMeetings
    getCourseInstanceStudent
    getCourseInstanceStudentAttendance
    getCourseInstanceStudents
    getCourseOfferingLinks
    getCourseOfferingSyllabus
    getCurrentAcademicTerm
    getCurrentAcademicYear
    getCustomFieldOptions
    getCustomFields
    getDataSlicerReport
    getDataSlicerReports
    getDegreeAudit
    getDegrees
    getDonation
    getDonor
    getEducationLevels
    getEntriesForAccount
    getEvent
    getEvents
    getFees
    getFileDownloadURL
    getFinancialAidAwardTypes
    getFinancialAidAwards
    getFinancialAidDisbursements
    getFinancialAidYears
    getFunds
    getGradeReport
    getInquiries
    getInquiry
    getInvoice
    getInvoices
    getLeadSources
    getLeads
    getLedgerAccounts
    getMealPlans
    getMyCourses
    getNews
    getOccupations
    getOrganization
    getOrganizationTypes
    getOrganizations
    getPayment
    getPaymentPlans
    getPendingCharges
    getPerson
    getPersonApplications
    getPersonCommunicationPlans
    getPersonLeads
    getPersonLocks
    getPersonOrganizations
    getPersonRelationships
    getPersonSIN
    getPersonSSN
    getPossibleDuplicatePeople
    getPrintLayouts
    getPrograms
    getProvinces
    getRaces
    getRefund
    getRelationshipTypes
    getRoleMembers
    getRoles
    getRoomPlans
    getStandardizedTests
    getStates
    getStudentAssignmentSubmissions
    getStudentBalances
    getStudentDefaultTuitionSchedules
    getStudentDiscipline
    getStudentInfo
    getStudentMealPlan
    getStudentPrograms
    getStudentRoomPlan
    getStudentStandardizedTests
    getStudentTermTuitionSchedules
    getTaggedPeople
    getTags
    getTermBillingInfo
    getTermCourseInstances
    getTermEnrollment
    getTermStudents
    getTodos
    getTransactions
    getTranscript
    getTransferCreditProgramGradeOptions
    getTuitionSchedules
    getUpdatedEnrollment
    getUpdatedPeople
    getUsers
    getVoidedTransactions
    invoicePendingCharges
    linkApplicationToPerson
    linkDonation
    linkInquiryToPerson
    postFinancialAidDisbursement
    removeAdvisorFromStudent
    removeDefaultTuitionScheduleFromStudent
    removeRole
    removeTag
    removeTermTuitionScheduleFromStudent
    removeUser
    requestBackup
    resubscribeEmailAddress
    searchOrganizations
    searchPeople
    setApplicationField
    setCustomField
    setLeadInfo
    setPersonBirthDate
    setPersonCitizenship
    setPersonGender
    setPersonHometown
    setPersonName
    setPersonRaceEthnicity
    setPersonSIN
    setPersonSSN
    setStudentAssignmentGrade
    setStudentEntranceTerm
    setStudentFinalGrade
    setStudentID
    setStudentMealPlan
    setStudentRoomPlan
    setStudentStandardizedTestSectionScore
    setTodoCompleted
    submitApplication
    unblockUser
    unlinkApplication
    unlinkDonation
    unsubscribeEmailAddress
    updateAddress
    updateApplicationFieldStatus
    updateApplicationStatus
    updateCourseInstanceAssignment
    updateCourseInstanceAssignmentGroup
    updateCourseOfferingLink
    updateEmailAddress
    updateInquiry
    updateLicensePlate
    updatePersonOrganization
    updatePhoneNumber
    updateStudentAttendance
    updateStudentCourseEnrollment
    updateStudentStandardizedTest
    updateStudentTermTuitionScheduleBracket
    uploadAssignmentSubmission
    uploadFile
  ])

  module Tasks
    def normalize_task(task)
      as_camel = task.to_s.camelize(:lower).delete_suffix('!')
      do_raise = task.to_s.end_with?('!')
      [as_camel, do_raise]
    end

    def raise_if_task_not_recognized(task)
      raise TaskNotFoundError unless API_TASKS.include? task
    end
  end
end
